version: '3'

networks:
  shared-network:
    driver: bridge

services:
  db:
    container_name: sales_db
    networks:
      - shared-network
    image: postgres:latest
    ports:
      - 5438:5432
    environment:
      - POSTGRES_PASSWORD=example