db:

  user: postgres
  host: localhost:5438
  name: postgres
  disableTLS: disable

web:

  address: localhost:7000
  debug: localhost:7001
  readtimeout: "5s"
  writetimeout: "5s"
  shutdowntimeout: "5s"

auth:

  privatekeyfile: private.pem
  keyid: 1
  algorithm: RS256

trace:

  url: http://localhost:9411/api/v2/spans
  service: sales-api
  probability: 1