db:

  user: postgres
  host: localhost:5438
  name: postgres
  disableTLS: disable

web:

  address: localhost:7000
  debug: localhost:7001
  readtimeout: "5s"
  writetimeout: "5s"
  shutdowntimeout: "5s"